- import_tasks: configure-operator.yml
  become: true
  tags: [never,configure-operator]
  when: configure_operator | default(true)

- import_tasks: chef-client.yml
  become: true
  tags: [never,chef-client]

- import_tasks: ceph-destroy-osds.yml
  become: true
  tags: [never,ceph-destroy-osds]

- import_tasks: configure-networking.yml
  become: true
  tags: [never,configure-networking]

- import_tasks: configure-apt.yml
  become: true
  tags: [never,configure-apt]
